const strokeMap = {
  "一": "https://www.twpen.com/bishun-animation/4e00-stroke-order.gif",
  "丁": "https://www.twpen.com/bishun-animation/4e01-stroke-order.gif",
  "七": "https://www.twpen.com/bishun-animation/4e03-stroke-order.gif",
  "三": "https://www.twpen.com/bishun-animation/4e09-stroke-order.gif",
  "上": "https://www.twpen.com/bishun-animation/4e0a-stroke-order.gif",
  "下": "https://www.twpen.com/bishun-animation/4e0b-stroke-order.gif",
  "不": "https://www.twpen.com/bishun-animation/4e0d-stroke-order.gif",
  "丑": "https://www.twpen.com/bishun-animation/4e11-stroke-order.gif",
  "丟": "https://www.twpen.com/bishun-animation/4e1f-stroke-order.gif",
  "並": "https://www.twpen.com/bishun-animation/4e26-stroke-order.gif",
  "中": "https://www.twpen.com/bishun-animation/4e2d-stroke-order.gif",
  "串": "https://www.twpen.com/bishun-animation/4e32-stroke-order.gif",
  "丸": "https://www.twpen.com/bishun-animation/4e38-stroke-order.gif",
  "主": "https://www.twpen.com/bishun-animation/4e3b-stroke-order.gif",
  "久": "https://www.twpen.com/bishun-animation/4e45-stroke-order.gif",
  "九": "https://www.twpen.com/bishun-animation/4e5d-stroke-order.gif",
  "也": "https://www.twpen.com/bishun-animation/4e5f-stroke-order.gif",
  "乳": "https://www.twpen.com/bishun-animation/4e73-stroke-order.gif",
  "了": "https://www.twpen.com/bishun-animation/4e86-stroke-order.gif",
  "事": "https://www.twpen.com/bishun-animation/4e8b-stroke-order.gif",
  "二": "https://www.twpen.com/bishun-animation/4e8c-stroke-order.gif",
  "五": "https://www.twpen.com/bishun-animation/4e94-stroke-order.gif",
  "井": "https://www.twpen.com/bishun-animation/4e95-stroke-order.gif",
  "些": "https://www.twpen.com/bishun-animation/4e9b-stroke-order.gif",
  "我": "6211"
};
